/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

import java.beans.Transient;

public class AppTest {
   
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting1", classUnderTest.getGreeting());
    } 
    @Test
    public void appHasHelloWorld() {
        App classUnderTest = new App();
        assertEquals("app should return 'Hello World!'", "Hello", classUnderTest.getGreetingHello());
    }
}
